services: 
  mongodb: 
    image: mongo
    container_name: mongo_db
    restart: always
    ports: 
      - 27017:27017 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo 
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    volumes:
      - mongodb_data:/data/db 


volumes:
  mongodb_data:
    driver: local
